# Generated by Django 4.2.9 on 2024-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dish_id',
            field=models.IntegerField(default=1),
        ),
    ]
