# Generated by Django 4.2.9 on 2024-03-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_remove_cartitem_dish_remove_cartitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
