# Generated by Django 4.2.9 on 2024-03-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_remove_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='address',
        ),
    ]
