# Generated by Django 4.2.9 on 2024-03-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0011_remove_cart_items_cartitem_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='items',
            new_name='cart',
        ),
    ]
