# Generated by Django 4.2.9 on 2024-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0012_rename_items_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('processing', 'Processing'), ('on_delivery', 'On delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
